################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.md", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Development Status :: 5 - Production/Stable",
		"License :: OSI Approved :: Apache Software License",
		"Programming Language :: Python :: 3",
	],
	description = "A python module for parsing of program arguments.",
	include_package_data = True,
	install_requires = [
		"jk_terminal_essentials",
	],
	keywords = [
		"program",
		"arguments",
		"commands",
		"options",
		"args",
	],
	license = "Apache2",
	name = "jk_argparsing",
	package_data = {
		"": [
		],
	},
	packages = [
		"jk_argparsing",
		"jk_argparsing.textmodel",
		"jk_argparsing.textprimitives",
		"jk_argparsing.impl",
	],
	scripts = [
	],
	version = '0.2023.2.8',
	zip_safe = False,
	long_description = readme(),
	long_description_content_type = "text/markdown",
)
