################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.md", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Programming Language :: Python :: 3",
		"Development Status :: 5 - Production/Stable",
		"License :: OSI Approved :: Apache Software License",
	],
	description = "A python module for parsing of program arguments.",
	download_url = "https://github.com/jkpubsrc/python-module-jk-argparsing/tarball/0.2019.9.11",
	include_package_data = False,
	install_requires = [
	],
	keywords = [
		"program",
		"arguments",
		"commands",
		"options",
		"args",
	],
	license = "Apache 2.0",
	name = "jk_argparsing",
	packages = [
		"jk_argparsing",
	],
	url = "https://github.com/jkpubsrc/python-module-jk-argparsing",
	version = "0.2020.8.15.1",
	zip_safe = False,
	long_description = readme(),
	long_description_content_type="text/markdown",
)
